### ISSUE TITLE
the middleware can't be installed for the actual FastAPI version

### ISSUE THREAD

**Issue by alexted** [trallnag/prometheus-fastapi-instrumentator#214] opened 2023-02-12 15:28 UTC
Hi! Since FastAPI version [0.91.0](https://github.com/tiangolo/fastapi/releases/tag/0.91.0), I started getting the following error when trying to run the application:
```bash
INFO:     Will watch for changes in these directories: ['/home/my_name/PycharmProjects/my-app']
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:     Started reloader process [15443] using WatchFiles
INFO:     Started server process [15472]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/home/my_name/.cache/pypoetry/virtualenvs/my-app-PzElRY_T-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/my_name/.cache/pypoetry/virtualenvs/my-app-PzElRY_T-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/my_name/.cache/pypoetry/virtualenvs/my-app-PzElRY_T-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/my_name/PycharmProjects/my-app/core/app/service.py", line 75, in integrate_monitoring_plugin
    Instrumentator(excluded_handlers=["/health", "/metrics"]).instrument(app).expose(app, include_in_schema=False)
  File "/home/my_name/.cache/pypoetry/virtualenvs/my-app-PzElRY_T-py3.10/lib/python3.10/site-packages/prometheus_fastapi_instrumentator/instrumentation.py", line 121, in instrument
    app.add_middleware(
  File "/home/my_name/.cache/pypoetry/virtualenvs/my-app-PzElRY_T-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started

ERROR:    Application startup failed. Exiting.
```

I initiate the application this way:
```python
def create_app() -> FastAPI:
    app = FastAPI()

    #blah-blah-blah

    @app.on_event("startup")
    async def integrate_monitoring_plugin():
        Instrumentator(excluded_handlers=["/health", "/metrics"]).instrument(app).expose(app, include_in_schema=False)

    return app
```

**Comment by Dencrash** [comment] 2023-02-14 12:00
We have the same problem with both the fastapi versions 0.91.0 and 0.92.0 being effected. It seems like adding a middleware after startup is not valid anymore, though they also fixed the fact that middlewares are initialized multiple times. Is there an alternative way to integrate the instrumentator?

**Comment by duffn** [comment] 2023-02-14 20:54
We're encountering the same issue. Here's where this was introduced in Starlette. https://github.com/encode/starlette/commit/51c1de1839ee187bb20de5748fca23baa37369c6#diff-3eb07c0eea72d98f1b844e07844c2a68b7c11c63956b67d5afdd9c7f79ab946fR135

**Comment by harochau** [comment] 2023-02-15 16:11
I have the same problem.
Maybe we can use https://github.com/stephenhillier/starlette_exporter instead? Does anybody have experience with that library, is it a drop-in replacement?

**Comment by alfaro28** [comment] 2023-02-16 02:34
Is there any reason to implement the instrumentator on the "startup" event? Just moving the instrumentator outside of the event makes things work

**Comment by jonathanherdt** [comment] 2023-02-21 08:16
> Is there any reason to implement the instrumentator on the "startup" event? Just moving the instrumentator outside of the event makes things work

[According to the maintainer](https://github.com/trallnag/prometheus-fastapi-instrumentator/issues/80):

> Prometheus expects a fully initialized ASGI client, where uvicorn now delays execution in newer versions. Closing.

**Comment by alfaro28** [comment] 2023-02-21 16:22
sorry I should have been more clear, what I'm currently doing is creating the instrumentator and "instrument" the app outside of the startup event, but actually "exposing" it on the startup event and seems to be working fine

**Comment by duffn** [comment] 2023-02-21 19:21
> sorry I should have been more clear, what I'm currently doing is creating the instrumentator and "instrument" the app outside of the startup event, but actually "exposing" it on the startup event and seems to be working fine

Can you share a bit of code here please?

**Comment by alfaro28** [comment] 2023-02-21 22:02
Sure,, just a quick note, I'm using `start_http_server` because I run my prometheus server on a diferent port, but I asume you could save the Instrumentator variable and just call `.expose` on the startup_event function

```
from fastapi import FastAPI
from prometheus_client import start_http_server
from prometheus_fastapi_instrumentator import Instrumentator

async def startup_event():
    start_http_server(8080)
    
app = FastAPI(
    on_startup=[startup_event]
)

Instrumentator(
    excluded_handlers=["/metrics"],
).instrument(app)
```

**Comment by harochau** [comment] 2023-02-23 12:42
can confirm, this works with the new Fastapi
`
instrumentator = Instrumentator().instrument(app)
@app.on_event("startup")
async def _startup():
    instrumentator.expose(app, endpoint='/metrics', tags=['metrics'])
`

**Comment by trallnag** [comment] 2023-02-25 22:56
> Is there any reason to implement the instrumentator on the "startup" event? Just moving the instrumentator outside of the event makes things work

The README was updated to use `startup` around 6 months ago due to #80. It is probably best to update the README again with the next release. Just tried it (while testing other things) and for me it works without `startup` fine.

Here are relevant dependencies:

```
❯ pip list
Package                           Version Editable project location
--------------------------------- ------- ----------------------------
fastapi                           0.92.0
prometheus-client                 0.16.0
prometheus-fastapi-instrumentator 100.0.0
starlette                         0.25.0
uvicorn                           0.20.0
```

The code:

```python
from fastapi import FastAPI

from prometheus_fastapi_instrumentator import Instrumentator

app = FastAPI()

@app.get("/app")
def read_main():
    return {"message": "Hello World from main app"}

Instrumentator().instrument(app).expose(app)
```

Reproducible examples would be great as I am not using the package actively anymore.

**Comment by trallnag** [comment] 2023-02-26 16:04
@alexted does this also happen if you use https://github.com/stephenhillier/starlette_exporter? I think it is related to how the prometheus client library works. In the unit tests of this package here I call the following function at the beginning of every relevant unit test: https://github.com/trallnag/prometheus-fastapi-instrumentator/blob/master/tests/helpers/utils.py#L4

Another solution seems to be to use a new registry for every unit test: https://github.com/rycus86/prometheus_flask_exporter/issues/17

Current version of prometheus-fastapi-instrumentator does not support passing custom registry, but this feature has already been merged as part of clean up and I will release it today

**Comment by saschnet** [comment] 2023-02-26 16:21
Is there anything pointing against the solution @alfaro28 / @harochau?

For me, it is working with all circumstances (unit tests + the app itself) and is much simpler than adding a new registry for every unit test etc.

**Comment by trallnag** [comment] 2023-02-26 16:23
@saschnet, I don't know 😆 I will update the README and switch to the example provided by @harochau

**Comment by AliSayyah** [comment] 2023-03-05 17:36
For now, I'm excluding 'prometheus_fastapi_instrumentator' when running tests.
I'm using 'pytest' so incase anyone having the same problem:
```python
instrumentor = None
    if "pytest" not in sys.modules:
        instrumentor = PrometheusFastApiInstrumentator(
            should_group_status_codes=False
        ).instrument(
            app,
        )
```
and:
```python 
    @app.on_event("startup")
    async def _startup() -> None: 
        ...
        if "pytest" not in sys.modules:
            setup_prometheus(app, instrumentor)
        ...

**Comment by trallnag** [comment] 2023-03-05 17:46
@alexted, probably related to #219

**Comment by trallnag** [comment] 2023-03-08 19:53
The `NameError` thing should be fixed now with the latest release https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/v5.11.0

**Comment by AliSayyah** [comment] 2023-03-08 20:33
> The `NameError` thing should be fixed now with the latest release https://github.com/trallnag/prometheus-fastapi-instrumentator/releases/tag/v5.11.0

Thanks. `NameError` is gone.

**Closed as completed** 2023-03-26 16:39 UTC
